### ISSUE TITLE
vue-animation

### ISSUE THREAD

**Issue by LinHuijuan** [LinHuijuan/front-end-record#21]
### vue中css动画原理
- 过渡动画原理
![enter princile](http://ww1.sinaimg.cn/large/a04ff18fgy1g09l8alveuj20ia04dgmn.jpg)
![leave principle](http://ww1.sinaimg.cn/large/a04ff18fgy1g09l5fkiykj20v007cad8.jpg)
```css
        .v-enter,
        .v-leave-to {
            opacity: 0;
        }
        
        .v-enter-active,
        .v-leave-active {
            transition: opacity 3s;
        }
```
```html
    <div id="root">
        <transition>
            <div v-if="show">hello world</div>
        </transition>
        <button @click="handleBtnClick">change</button>

    </div>
    <script>
        var vm = new Vue({
            el: '#root',
            data: {
                show: true
            },
            methods: {
                handleBtnClick: function() {
                    this.show = !this.show
                }
            }
        })
    </script>
```

### 在vue中使用animate.css库
- 无引入的写法
```css
        @keyframes bounce-in {
            0% {
                transform: scale(0);
            }
            50% {
                transform: scale(1.5);
            }
            100% {
                transform: scale(1);
            }
        }
        
        .enter {
            transform-origin: left center;
            animation: bounce-in 3s;
        }
        
        .leave {
            transform-origin: left center;
            animation: bounce-in 3s reverse;
        }
```
```html
    <div id="root">
        <!-- <transition name="fade" enter-active-class="active" leave-active-class="leave"> -->
        <transition enter-active-class="enter" leave-active-class="leave">
            <div v-if="show">hello world</div>
        </transition>
        <button @click="handleBtnClick">change</button>
    </div>
    
    <script>
        var vm = new Vue({
            el: '#root',
            data: {
                show: true
            },
            methods: {
                handleBtnClick: function() {
                    this.show = !this.show
                }
            }
        })
    </script>
```
- 引入的写法
```html
    <style></style>
    
    <div id="root">
        <transition enter-active-class="animate bounceIn" leave-active-class="animate bounceOut">
            <div v-if="show">hello world</div>
        </transition>
        <button @click="handleBtnClick">change</button>
    </div>
```
### 在vue中同时使用过渡和动画
- 初次显示也有动画
```
    <div id="root">
        <!-- appear使第一次显示也有动画 -->
        <transition appear
        enter-active-class="animate bounceIn"
        leave-active-class="animate bounceOut"
        appear-avtive-class="animate bounceIn">
            <div v-if="show">hello world</div>
        </transition>
        <button @click="handleBtnClick">change</button>
    </div>
```
- 同时过渡和动画并统一时长
```css
    .fade-enter,
        .fade-leave-to {
            opacity: 0;
        }

        .fade-enter-active,
        .fade-leave-active {
            transition: opacity 5s;
        }
```
```html
    <div id="root">
        <!-- 为了避免animate与transiton的动画时长不一致，需统一 -->
        <!-- 第一种：type="transition" -->
        <!-- 第二种：:duration="10000" 默认单位：ms -->
        <!-- 第三种 -->
        <transition name="fade"  :duration="{enter:10000,leave:5000}" appear enter-active-class="animate bounceIn fade-enter-active" leave-active-class="animate bounceOut fade-leave-active" appear-avtive-class="animate bounceIn">
            <div v-if="show">hello world</div>
        </transition>
        <button @click="handleBtnClick">change</button>
    </div>
```

### vue中的js动画与velocity.js的结合
- js动画钩子
```html
    <div id="root">
        <transition @before-enter="handleBeforeEnter" 
                    @enter="handleEnter" 
                    @after-enter="handleAfterEnter">
            <div v-show="show">hello world</div>
        </transition>
        <button @click="handleBtnClick">toggle</button>
    </div>
    <script>
        var vm = new Vue({
            el: '#root',
            data: {
                show: true
            },
            methods: {
                handleBtnClick: function() {
                    this.show = !this.show
                },
                //js动画钩子
                //el指transition包裹的元素
                handleBeforeEnter: function(el) {
                    el.style.color = 'red';
                },
                //done是回调函数
                handleEnter: function(el, done) {
                    setTimeout(() => {
                        el.style.color = 'yellow'
                    }, 2000)
                    setTimeout(() => {
                        done()
                    }, 4000)
                },
                //由done()触发
                handleAfterEnter: function(el) {
                    el.style.color = 'blue'
                }
            }
        })
    </script>
```
出场动画：把```enter```换成```leave```即可
- velocity.js
```js
            methods: {
                handleBtnClick: function() {
                    this.show = !this.show
                },
                handleBeforeEnter: function(el) {
                    el.style.opacity = 0;
                },
                handleEnter: function(el, done) {
                    Velocity(el, {
                        opacity: 1
                    }, {
                        duration: 1000,
                        complete: done
                    })
                },
                handleAfterEnter: function(el) {
                    el.style.color = 'blue'
                }
            }
```
